# (C) Copyright 2021-2024 Hewlett Packard Enterprise Development LP
instance_name = "Greenboat VM107 VM"
location = "HPE"
space = "Default"
cloud = "HPE GreenLake VMaaS Cloud-Trial2"
datastore = "toro-gl1-trial2-Vol1"
network = "Green-Net"
group = "Department B Group"
resource_pool = "ComputeResourcePool"
compute_folder = "ComputeFolder"
instance_type = "Ubuntu-vm"
layout = "Ubuntu-20"
template = "ubuntu-20"
service_plan = "G1-Small"
environment = "Dev"
